name: Update README

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@dev

      - uses: adisus2-plasma/adisus2-plasma@dev
        env:
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
        with:
          commit_message: Update generated README
          branch: dev
          commit_user_name: adisus2-plasma
          commit_user_email: actions@github.com
          commit_author: adisus2-plasma <actions@github.com>
